backend:
  name: git-gateway
  repo: 07lonnie/LA-GACELA
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/6f935bce-10e7-4f4f-acee-854e0d188d8a/pkce
  auth_token_endpoint: /sites/6f935bce-10e7-4f4f-acee-854e0d188d8a/token
  gateway_url: https://gateway.decapbridge.com

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://la-gacela.vercel.app

media_folder: "fotos/subidas"
public_folder: "fotos/subidas"

collections:
  - name: "noticias"
    label: "Noticias"
    folder: "contenido/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["politica", "internacionales", "espectaculos", "deportes"] }
      - { label: "Autor", name: "autor", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - { label: "Bajada", name: "bajada", widget: "text" }
      - { label: "Imagen de Portada", name: "thumbnail", widget: "image", required: false }
      - { label: "Pie de Foto", name: "pie_foto", widget: "string", required: false }
      - { label: "Video YouTube", name: "video_url", widget: "string", required: false }
      - { label: "Cuerpo de la Noticia", name: "body", widget: "markdown" }